import "../globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import { ToastProvider } from "@/components/Toastcontainer";
import { SessionProvider } from "next-auth/react";
import { ThemeProvider } from "next-themes";


export const metadata: Metadata = {
  title: "Viraj multipurpose hall",
  description: "Generated by sj",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) 
{


  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        <SessionProvider>
 <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
            
          >
        {children}
          </ThemeProvider>

               <ToastProvider aria-label="Notification" />
        </SessionProvider>
        </body>
    </html>
  );
}



