FROM node:18-alpine AS base

RUN apk update
RUN apk add --no-cache libc6-compat

RUN npm install -g pnpm
RUN npm install -g turbo

WORKDIR /app

FROM base AS prepare

COPY . .

RUN turbo prune web --docker


# 
FROM base AS builder

COPY --from=prepare /app/out/json/ .

RUN pnpm install 

COPY --from=prepare /app/out/full/ .

ENV NEXT_PUBLIC_Backend_URL="https://fe.virajmultipurposehall.site/backend"

RUN pnpm turbo build


# 
FROM base AS runner

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs
USER nextjs

COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/.next/static ./apps/web/.next/static
COPY --from=builder --chown=nextjs:nodejs /app/apps/web/public ./apps/web/public

CMD ["node", "apps/web/server.js"]









# FROM node:18-alpine

# RUN npm install -g pnpm

# # ARG BACKEND_URL
# # ENV BACKEND_URL=${BACKEND_URL}

# WORKDIR /app

# COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
# COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml
# COPY ./package.json ./package.json
# COPY ./turbo.json ./turbo.json

# COPY ./packages ./packages
# COPY ./apps/web ./apps/web

# RUN pnpm install --frozen-lockfile

# RUN pnpm build

# EXPOSE 3000

# CMD ["pnpm", "run", "start:web"]
