import "../globals.css";
import "@repo/ui/styles.css";
import type { Metadata } from "next";
import LogoPage from "@/components/Signupnav";
import { ToastProvider } from "@/components/Toastcontainer";
import { SessionProvider } from "next-auth/react";


export const metadata: Metadata = {
  title: "Viraj multipurpose hall",
  description: "Generated by sj",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
           <SessionProvider>
        <LogoPage />
         <ToastProvider aria-label="Notification" /> 
        {children}
     </SessionProvider>
        </body>
    </html>
  );
}
